In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import pandas as pd
import numpy as np

In [12]:
data=pd.read_excel('/content/drive/MyDrive/FurahaAdmissionsAllClinics (2).xlsx')

In [13]:
data.head()

,FurahaAdmissionsAllClinics_Id,ChildsName_First,ChildsName_Last,Residence_Line1,Residence_City,Residence_State,Residence_Country,Residence_CountryCode,AdmissionNumber,DateOfBirth2,...,Comments,HowDidYouKnowAboutFuraha,HaveYouSignedOurPictureConsentForm,AssessedBy_First,AssessedBy_Last,Signature,Entry_Status,Entry_DateCreated,Entry_DateSubmitted,Entry_DateUpdated
0,918,Atkin,Ngige,Kaaga Kambakia,Sub county,Meru,Kenya,KE,FCME/543/2026,2022-10-21 00:00:00,...,Attend sessions every monday,Reffered from Meru teaching and refferal hospital,Yes,Jadlyne,Makena,NaN,Submitted,2026-08-20 06:42:00,2026-08-20 06:42:00,2026-08-20 06:42:00
1,917,Jayden,Mshindi,Kitheo,TIGANIA,Meru,Kenya,KE,FCMK/272/2026,2024-09-08 00:00:00,...,To start attending therapy sessions on Tuesada...,referred by a former furaha parent.,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-05 09:32:00,2026-08-05 09:32:00,2026-08-05 09:32:00
2,916,Annaya,Charlotte,Makutano,Sub county,Meru,Kenya,KE,FCME/542/2026,2025-05-20 00:00:00,...,"To start therapy sessions on Mondays ,Wednesd...",Referred by a friend.,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-03 09:48:00,2026-08-03 09:48:00,2026-08-03 09:57:00
3,915,Christine,Karimi,Katheri,Sub county,Meru,Kenya,KE,FCME/541/2026,2013-11-28 00:00:00,...,To start attending therapy sessions on Tuesday...,Referred from Githongo sub-county hospital,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-03 08:44:00,2026-08-03 08:44:00,2026-08-03 08:44:00
4,914,Ray,Israel Mureti,Milimani,Sub county,Meru,Kenya,KE,FCME/540/2026,2019-12-08 00:00:00,...,To come thrice a week,A friend of Furaha,Yes,Evylon,Gitau,NaN,Submitted,2026-08-03 07:21:00,2026-08-03 07:21:00,2026-08-03 07:21:00

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 909 entries, 0 to 908
Data columns (total 94 columns):
 #   Column                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                  --------------  -----
 0   FurahaAdmissionsAllClinics_Id                                                                           909 non-null    int64
 1   ChildsName_First                                                                                        908 non-null    object
 2   ChildsName_Last                                                                                         908 non-null    object
 3   Residence_Line1                                                                                         433 non-null    object
 4   Residence_City                                                                                          447 non-null    object
 5   Residence_State                                                                                         512 non-null    object
 6   Residence_Country                                                                                       147 non-null    object
 7   Residence_CountryCode                                                                                   147 non-null    object
 8   AdmissionNumber                                                                                         906 non-null    object
 9   DateOfBirth2                                                                                            798 non-null    object
 10  OtherSiblings                                                                                           391 non-null    object
 11  GuardianParticulars_First                                                                               773 non-null    object
 12  GuardianParticulars_Last                                                                                763 non-null    object
 13  Relationship                                                                                            909 non-null    object
 14  Assessment                                                                                              909 non-null    object
 15  Phone                                                                                                   734 non-null    object
 16  DateOfAssessment                                                                                        771 non-null    datetime64[ns]
 17  ChiefComplainConcernsExpectations                                                                       471 non-null    object
 18  MedicalHistories_FormOfDelivery                                                                         909 non-null    object
 19  MedicalHistories_AntenatalMedicalHx                                                                     312 non-null    object
 20  MedicalHistories_PerinatalPostnatalMedicalHx                                                            339 non-null    object
 21  MedicalHistories_PersonalFamilySocialStatus                                                             345 non-null    object
 22  MedicalHistories_PhysicalExamination                                                                    343 non-null    object
 23  Allergies                                                                                               909 non-null    object
 24  SkinProblems                                                                                            909 non-null    object
 25  HearingProblems                                                                                         909 non-null    object
 26  SpeakingProblems                                                                                        909 non-null    object
 27  PhysicalProblems                                                                                        909 non-null    object
 28  PsychologicalProblems                                                                                   909 non-null    object
 29  AnyOtherProblems                                                                                        909 non-null    object
 30  AnyOtherCondition                                                                                       71 non-null     object
 31  GrowthParameters_BirthWeightAndHeight                                                                   215 non-null    object
 32  HairColorDistribution                                                                                   253 non-null    object
 33  ObservableFeaturesAnyNoticableScarDeformity2                                                            115 non-null    object
 34  OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_HeadControl                             909 non-null    object
 35  OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_TrunkStablity                           909 non-null    object
 36  OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_RollingOver                             909 non-null    object
 37  OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Sitting                                 909 non-null    object
 38  OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Crawling                                908 non-null    object
 39  OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Standing                                909 non-null    object
 40  OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Walking                                 907 non-null    object
 41  OccupationalPerformanceAreas_FineMotor_EyeTracking                                                      908 non-null    object
 42  OccupationalPerformanceAreas_FineMotor_EyeHandCordination                                               906 non-null    object
 43  OccupationalPerformanceAreas_FineMotor_BilateralHandUse                                                 905 non-null    object
 44  OccupationalPerformanceAreas_FineMotor_Grasp                                                            907 non-null    object
 45  OccupationalPerformanceAreas_FineMotor_Manipulation                                                     907 non-null    object
 46  OccupationalPerformanceAreas_FineMotor_Release                                                          906 non-null    object
 47  OccupationalPerformanceAreas_FineMotor_MuscleTone_MuscleToneDescription                                 907 non-null    object
 48  OccupationalPerformanceAreas_FineMotor_Sensory_Auditory                                                 908 non-null    object
 49  OccupationalPerformanceAreas_FineMotor_Sensory_Vestibular                                               905 non-null    object
 50  OccupationalPerformanceAreas_FineMotor_Sensory_Visual                                                   907 non-null    object
 51  OccupationalPerformanceAreas_FineMotor_Sensory_Tactile                                                  903 non-null    object
 52  OccupationalPerformanceAreas_FineMotor_Sensory_BalanceCoordinationNotes                                 94 non-null     object
 53  OccupationalPerformanceAreas_FineMotor_Sensory_PropioceptionVestibularNotes                             109 non-null    object
 54  OccupationalPerformanceAreas_FineMotor_Sensory_AuditoryNotes                                            121 non-null    object
 55  OccupationalPerformanceAreas_FineMotor_Sensory_TactileNotes                                             91 non-null     object
 56  OccupationalPerformanceAreas_FineMotor_Sensory_PerceptualNotes                                          40 non-null     object
 57  OccupationalPerformanceAreas_FineMotor_Sensory_OlfactoryNotes                                           42 non-null     object
 58  OccupationalPerformanceAreas_FineMotor_Sensory_GastatoryNotes                                           42 non-null     object
 59  OccupationalPerformanceAreas_FineMotor_Sensory_VisualNotes                                              93 non-null     object
 60  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_FeedingEating                    332 non-null    object
 61  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_GroomingDressingSkills           326 non-null    object
 62  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_Toileting                        331 non-null    object
 63  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_SkillsInterests                  86 non-null     object
 64  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CommunicationSkills              202 non-null    object
 65  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_HygieneSkills                    156 non-null    object
 66  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_Planning        40 non-null     object
 67  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_Memory          43 non-null     object
 68  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_Organization    35 non-null     object
 69  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_ProblemSolving  39 non-null     object
 70  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_Language                         99 non-null     object
 71  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_PlayLeisure                      192 non-null    object
 72  OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_School                           247 non-null    object
 73  IdentifiedNeedForOccupationalTherapy_ClearNeedForOTOccupationalNeedsIdentifed                           909 non-null    object
 74  IdentifiedNeedForOccupationalTherapy_InterventionToSupportWellnessAndorPreventDysfunction               909 non-null    object
 75  IdentifiedNeedForOccupationalTherapy_NeedForOTIntervetionToRestoreimproveFunction                       909 non-null    object
 76  IdentifiedNeedForOccupationalTherapy_NeedForExtensiveOTIntervetionToImproveFunction                     909 non-null    object
 77  IdentifiedNeedForOccupationalTherapy_RefferalToFolowUpServiceAlsoRecommended                            909 non-null    object
 78  DXOTImpression                                                                                          717 non-null    object
 79  OTProblemsIdentified                                                                                    442 non-null    object
 80  Objectives                                                                                              288 non-null    object
 81  AssistiveDeviceGivenOlinekSuit                                                                          78 non-null     object
 82  InterventionPlan                                                                                        362 non-null    object
 83  HomeProgramme                                                                                           222 non-null    object
 84  Comments                                                                                                235 non-null    object
 85  HowDidYouKnowAboutFuraha                                                                                368 non-null    object
 86  HaveYouSignedOurPictureConsentForm                                                                      909 non-null    object
 87  AssessedBy_First                                                                                        462 non-null    object
 88  AssessedBy_Last                                                                                         431 non-null    object
 89  Signature                                                                                               215 non-null    object
 90  Entry_Status                                                                                            909 non-null    object
 91  Entry_DateCreated                                                                                       909 non-null    datetime64[ns]
 92  Entry_DateSubmitted                                                                                     908 non-null    datetime64[ns]
 93  Entry_DateUpdated                                                                                       909 non-null    datetime64[ns]
dtypes: datetime64[ns](4), int64(1), object(89)
memory usage: 667.7+ KB

In [15]:
data.describe()

,FurahaAdmissionsAllClinics_Id,DateOfAssessment,Entry_DateCreated,Entry_DateSubmitted,Entry_DateUpdated
count,909.000000,771,909,908,909
mean,462.299230,2021-12-04 05:15:38.521400832,2024-04-14 21:45:24.488448768,2024-04-15 13:55:16.387665152,2024-06-18 21:02:20.726072576
min,6.000000,2008-01-31 00:00:00,2022-05-20 09:02:00,2022-05-20 09:02:00,2022-08-12 08:28:00
25%,235.000000,2018-11-19 12:00:00,2023-11-03 08:27:00,2023-11-03 08:27:00,2023-11-22 08:49:00
50%,462.000000,2021-09-13 00:00:00,2023-11-23 07:59:00,2023-11-23 08:00:00,2024-02-21 06:53:00
75%,690.000000,2024-11-11 12:00:00,2024-08-28 10:43:00,2024-08-28 11:10:00,2024-11-29 11:30:00
max,918.000000,2028-06-06 00:00:00,2026-08-20 06:42:00,2026-08-20 06:42:00,2026-08-20 06:42:00
std,263.589365,NaN,NaN,NaN,NaN

In [16]:
data_filtered = data[data['AdmissionNumber'].astype(str).str.startswith(('RI', 'FCME'), na=False)]

display(data_filtered.head())

,FurahaAdmissionsAllClinics_Id,ChildsName_First,ChildsName_Last,Residence_Line1,Residence_City,Residence_State,Residence_Country,Residence_CountryCode,AdmissionNumber,DateOfBirth2,...,Comments,HowDidYouKnowAboutFuraha,HaveYouSignedOurPictureConsentForm,AssessedBy_First,AssessedBy_Last,Signature,Entry_Status,Entry_DateCreated,Entry_DateSubmitted,Entry_DateUpdated
0,918,Atkin,Ngige,Kaaga Kambakia,Sub county,Meru,Kenya,KE,FCME/543/2026,2022-10-21 00:00:00,...,Attend sessions every monday,Reffered from Meru teaching and refferal hospital,Yes,Jadlyne,Makena,NaN,Submitted,2026-08-20 06:42:00,2026-08-20 06:42:00,2026-08-20 06:42:00
2,916,Annaya,Charlotte,Makutano,Sub county,Meru,Kenya,KE,FCME/542/2026,2025-05-20 00:00:00,...,"To start therapy sessions on Mondays ,Wednesd...",Referred by a friend.,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-03 09:48:00,2026-08-03 09:48:00,2026-08-03 09:57:00
3,915,Christine,Karimi,Katheri,Sub county,Meru,Kenya,KE,FCME/541/2026,2013-11-28 00:00:00,...,To start attending therapy sessions on Tuesday...,Referred from Githongo sub-county hospital,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-03 08:44:00,2026-08-03 08:44:00,2026-08-03 08:44:00
4,914,Ray,Israel Mureti,Milimani,Sub county,Meru,Kenya,KE,FCME/540/2026,2019-12-08 00:00:00,...,To come thrice a week,A friend of Furaha,Yes,Evylon,Gitau,NaN,Submitted,2026-08-03 07:21:00,2026-08-03 07:21:00,2026-08-03 07:21:00
5,913,kelvin,ndereba,Current Location,Sub county,Meru,Kenya,KE,FCME/539/2026,2015-11-11 00:00:00,...,Booked for therapy sessions on Wednesday,Referred from Githongo office for children wit...,Yes,Rosemary,kawira,NaN,Submitted,2026-07-17 12:37:00,2026-07-17 12:37:00,2026-07-17 12:37:00

In [17]:
data = data[~data['AdmissionNumber'].str.startswith('FCMER', na=False)]
display(data.head())

,FurahaAdmissionsAllClinics_Id,ChildsName_First,ChildsName_Last,Residence_Line1,Residence_City,Residence_State,Residence_Country,Residence_CountryCode,AdmissionNumber,DateOfBirth2,...,Comments,HowDidYouKnowAboutFuraha,HaveYouSignedOurPictureConsentForm,AssessedBy_First,AssessedBy_Last,Signature,Entry_Status,Entry_DateCreated,Entry_DateSubmitted,Entry_DateUpdated
0,918,Atkin,Ngige,Kaaga Kambakia,Sub county,Meru,Kenya,KE,FCME/543/2026,2022-10-21 00:00:00,...,Attend sessions every monday,Reffered from Meru teaching and refferal hospital,Yes,Jadlyne,Makena,NaN,Submitted,2026-08-20 06:42:00,2026-08-20 06:42:00,2026-08-20 06:42:00
1,917,Jayden,Mshindi,Kitheo,TIGANIA,Meru,Kenya,KE,FCMK/272/2026,2024-09-08 00:00:00,...,To start attending therapy sessions on Tuesada...,referred by a former furaha parent.,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-05 09:32:00,2026-08-05 09:32:00,2026-08-05 09:32:00
2,916,Annaya,Charlotte,Makutano,Sub county,Meru,Kenya,KE,FCME/542/2026,2025-05-20 00:00:00,...,"To start therapy sessions on Mondays ,Wednesd...",Referred by a friend.,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-03 09:48:00,2026-08-03 09:48:00,2026-08-03 09:57:00
3,915,Christine,Karimi,Katheri,Sub county,Meru,Kenya,KE,FCME/541/2026,2013-11-28 00:00:00,...,To start attending therapy sessions on Tuesday...,Referred from Githongo sub-county hospital,Yes,Festus,Kahuthu,NaN,Submitted,2026-08-03 08:44:00,2026-08-03 08:44:00,2026-08-03 08:44:00
4,914,Ray,Israel Mureti,Milimani,Sub county,Meru,Kenya,KE,FCME/540/2026,2019-12-08 00:00:00,...,To come thrice a week,A friend of Furaha,Yes,Evylon,Gitau,NaN,Submitted,2026-08-03 07:21:00,2026-08-03 07:21:00,2026-08-03 07:21:00

In [18]:
display(data_filtered.tail())

,FurahaAdmissionsAllClinics_Id,ChildsName_First,ChildsName_Last,Residence_Line1,Residence_City,Residence_State,Residence_Country,Residence_CountryCode,AdmissionNumber,DateOfBirth2,...,Comments,HowDidYouKnowAboutFuraha,HaveYouSignedOurPictureConsentForm,AssessedBy_First,AssessedBy_Last,Signature,Entry_Status,Entry_DateCreated,Entry_DateSubmitted,Entry_DateUpdated
904,10,Nathan,MUSOI,NaN,NaN,NaN,NaN,NaN,FCME/293/2022,NaN,...,NaN,Refferal from ripples,Yes,NaN,NaN,NaN,Submitted,2022-06-14 06:03:00,2022-06-14 06:03:00,2023-11-02 09:41:00
905,9,Emmanuel,Kithinji,NaN,NaN,NaN,NaN,NaN,FCME/292/2022,NaN,...,NaN,Was referred by a former client,Yes,NaN,NaN,NaN,Submitted,2022-05-30 11:12:00,2022-05-30 11:12:00,2023-11-02 09:39:00
906,8,Victor,Gichuki,NaN,NaN,NaN,NaN,NaN,FCME/291/2022,NaN,...,NaN,Reffered by MCA Murega,Yes,NaN,NaN,NaN,Submitted,2022-05-27 09:26:00,2022-05-27 09:26:00,2023-11-02 09:35:00
907,7,Victor,Mwiti,NaN,NaN,NaN,NaN,NaN,FCME/14/2016,2013-03-10 00:00:00,...,NaN,Was referred by another parent,Yes,NaN,NaN,NaN,Submitted,2022-05-26 07:04:00,2022-05-26 07:04:00,2023-11-16 10:57:00
908,6,Keziah,Mwendwa,NaN,NaN,NaN,NaN,NaN,FCME/290/2022,NaN,...,NaN,Referral from another client,Yes,NaN,NaN,NaN,Submitted,2022-05-20 09:02:00,2022-05-20 09:02:00,2023-11-02 09:21:00

In [19]:
data_filtered.loc[:, 'AdmissionNumber'] = data_filtered['AdmissionNumber'].astype(str).str.upper()
data_filtered.loc[:, 'ChildsName_First'] = data_filtered['ChildsName_First'].astype(str).str.upper()
data_filtered.loc[:, 'ChildsName_Last'] = data_filtered['ChildsName_Last'].astype(str).str.upper()

display(data_filtered[['AdmissionNumber', 'ChildsName_First', 'ChildsName_Last']].head())

  AdmissionNumber ChildsName_First ChildsName_Last
0   FCME/543/2026            ATKIN           NGIGE
2   FCME/542/2026           ANNAYA       CHARLOTTE
3   FCME/541/2026        CHRISTINE          KARIMI
4   FCME/540/2026              RAY   ISRAEL MURETI
5   FCME/539/2026           KELVIN         NDEREBA

In [20]:
print(f"Shape before dropping duplicates: {data_filtered.shape}")

Shape before dropping duplicates: (557, 94)

In [21]:
print(data_filtered.columns.tolist())

['FurahaAdmissionsAllClinics_Id', 'ChildsName_First', 'ChildsName_Last', 'Residence_Line1', 'Residence_City', 'Residence_State', 'Residence_Country', 'Residence_CountryCode', 'AdmissionNumber', 'DateOfBirth2', 'OtherSiblings', 'GuardianParticulars_First', 'GuardianParticulars_Last', 'Relationship', 'Assessment', 'Phone', 'DateOfAssessment', 'ChiefComplainConcernsExpectations', 'MedicalHistories_FormOfDelivery', 'MedicalHistories_AntenatalMedicalHx', 'MedicalHistories_PerinatalPostnatalMedicalHx', 'MedicalHistories_PersonalFamilySocialStatus', 'MedicalHistories_PhysicalExamination', 'Allergies', 'SkinProblems', 'HearingProblems', 'SpeakingProblems', 'PhysicalProblems', 'PsychologicalProblems', 'AnyOtherProblems', 'AnyOtherCondition', 'GrowthParameters_BirthWeightAndHeight', 'HairColorDistribution', 'ObservableFeaturesAnyNoticableScarDeformity2', 'OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_HeadControl', 'OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_TrunkStablity', 'OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_RollingOver', 'OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Sitting', 'OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Crawling', 'OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Standing', 'OccupationalPerformanceAreas_DevelopmentalComponents_GrossMotor_Walking', 'OccupationalPerformanceAreas_FineMotor_EyeTracking', 'OccupationalPerformanceAreas_FineMotor_EyeHandCordination', 'OccupationalPerformanceAreas_FineMotor_BilateralHandUse', 'OccupationalPerformanceAreas_FineMotor_Grasp', 'OccupationalPerformanceAreas_FineMotor_Manipulation', 'OccupationalPerformanceAreas_FineMotor_Release', 'OccupationalPerformanceAreas_FineMotor_MuscleTone_MuscleToneDescription', 'OccupationalPerformanceAreas_FineMotor_Sensory_Auditory', 'OccupationalPerformanceAreas_FineMotor_Sensory_Vestibular', 'OccupationalPerformanceAreas_FineMotor_Sensory_Visual', 'OccupationalPerformanceAreas_FineMotor_Sensory_Tactile', 'OccupationalPerformanceAreas_FineMotor_Sensory_BalanceCoordinationNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_PropioceptionVestibularNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_AuditoryNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_TactileNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_PerceptualNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_OlfactoryNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_GastatoryNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_VisualNotes', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_FeedingEating', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_GroomingDressingSkills', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_Toileting', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_SkillsInterests', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CommunicationSkills', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_HygieneSkills', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_Planning', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_Memory', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_Organization', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_CognitiveAbility_ProblemSolving', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_Language', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_PlayLeisure', 'OccupationalPerformanceAreas_FineMotor_Sensory_ActivitiesOfDailyLiving_School', 'IdentifiedNeedForOccupationalTherapy_ClearNeedForOTOccupationalNeedsIdentifed', 'IdentifiedNeedForOccupationalTherapy_InterventionToSupportWellnessAndorPreventDysfunction', 'IdentifiedNeedForOccupationalTherapy_NeedForOTIntervetionToRestoreimproveFunction', 'IdentifiedNeedForOccupationalTherapy_NeedForExtensiveOTIntervetionToImproveFunction', 'IdentifiedNeedForOccupationalTherapy_RefferalToFolowUpServiceAlsoRecommended', 'DXOTImpression', 'OTProblemsIdentified', 'Objectives', 'AssistiveDeviceGivenOlinekSuit', 'InterventionPlan', 'HomeProgramme', 'Comments', 'HowDidYouKnowAboutFuraha', 'HaveYouSignedOurPictureConsentForm', 'AssessedBy_First', 'AssessedBy_Last', 'Signature', 'Entry_Status', 'Entry_DateCreated', 'Entry_DateSubmitted', 'Entry_DateUpdated']

In [22]:
print(f"Shape before dropping duplicates: {data_filtered.shape}")

duplicate_subset_cols = [
    'AdmissionNumber',
    'ChildsName_First',
    'ChildsName_Last',
    'Residence_Line1',
    'Residence_City',
    'Phone'
]

# Drop duplicates based on the defined subset of columns
data_unique = data_filtered.drop_duplicates(subset=duplicate_subset_cols)

print(f"Shape after dropping duplicates: {data_unique.shape}")
display(data_unique[['AdmissionNumber', 'ChildsName_First', 'ChildsName_Last', 'Residence_City', 'Phone']].head())

Shape before dropping duplicates: (557, 94)
Shape after dropping duplicates: (555, 94)

  AdmissionNumber ChildsName_First ChildsName_Last Residence_City       Phone
0   FCME/543/2026            ATKIN           NGIGE     Sub county  0721109216
2   FCME/542/2026           ANNAYA       CHARLOTTE     Sub county  0769363800
3   FCME/541/2026        CHRISTINE          KARIMI     Sub county   011543332
4   FCME/540/2026              RAY   ISRAEL MURETI     Sub county  0724406343
5   FCME/539/2026           KELVIN         NDEREBA     Sub county  0112032608

In [23]:
dropped_duplicates = data_filtered[data_filtered.duplicated(subset=duplicate_subset_cols, keep='first')]

print("Dropped duplicates (Child's Name, Admission Number, Residence City, Phone):")
display(dropped_duplicates[['ChildsName_First', 'ChildsName_Last', 'AdmissionNumber', 'Residence_City', 'Phone']])

Dropped duplicates (Child's Name, Admission Number, Residence City, Phone):

    ChildsName_First ChildsName_Last AdmissionNumber Residence_City Phone
859         EMMANUEL           GITAU   FCME/281/2023            NaN   NaN
860          ABIGAEL          KANANU   FCME/282/2023            NaN   NaN

In [24]:
output_path = '/content/drive/MyDrive/FurahaAdmissionsUnique.csv'
data_unique.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/FurahaAdmissionsUnique.csv